<a href="https://colab.research.google.com/github/duressa-feyissa/Machine-Learning/blob/main/Project/Life_Expectancy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import chardet

# **1. Load Data**

In [22]:
with open("data.csv", "rb") as file:
    raw_data = file.read()

result = chardet.detect(raw_data)
encoding = result['encoding']

In [23]:
dataset = pd.read_csv("data.csv", encoding=encoding)

In [24]:
dataset.sample(5)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
2462,Sudan,2001,Developing,58.9,283,71,1.81,28.880697,NaN,4362,...,66.0,2.96,66.0,0.2,377.525445,279455.0,NaN,NaN,0.399,5.6
468,Cambodia,2011,Developing,67.0,19,13,2.12,60.185918,88.0,722,...,87.0,5.64,88.0,0.3,882.491462,14537886.0,11.0,11.2,0.533,10.7
2474,Suriname,2005,Developing,68.9,25,0,4.47,418.920661,83.0,0,...,84.0,6.78,83.0,0.6,3595.885500,498946.0,3.5,3.4,0.672,11.3
2691,Turkmenistan,2012,Developing,65.6,22,7,2.75,579.412824,98.0,0,...,98.0,1.96,97.0,0.1,6675.262954,5267839.0,3.2,3.3,0.672,10.7
585,Colombia,2006,Developing,73.1,147,15,4.53,62.437108,93.0,0,...,94.0,6.11,93.0,0.1,379.787760,43835722.0,2.3,2.1,0.669,11.5

# **2. Understand the Data**

In [25]:
#Get a summary of our data frame
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2928 entries, 0 to 2927
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2928 non-null   object
 1   Year                             2928 non-null   int64
 2   Status                           2928 non-null   object
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   int64
 5   infant deaths                    2928 non-null   int64
 6   Alcohol                          2735 non-null   float64
 7   percentage expenditure           2928 non-null   float64
 8   Hepatitis B                      2375 non-null   float64
 9   Measles                          2928 non-null   int64
 10   BMI                             2896 non-null   float64
 11  under-five deaths                2928 non-null   int64
 12  Polio                            2909 non-null   float64
 13  Total expenditure                2702 non-null   float64
 14  Diphtheria                       2909 non-null   float64
 15   HIV/AIDS                        2928 non-null   float64
 16  GDP                              2485 non-null   float64
 17  Population                       2284 non-null   float64
 18   thinness  1-19 years            2896 non-null   float64
 19   thinness 5-9 years              2896 non-null   float64
 20  Income composition of resources  2768 non-null   float64
 21  Schooling                        2768 non-null   float64
dtypes: float64(15), int64(5), object(2)
memory usage: 503.4+ KB

In [26]:
#Get a statistical summary of the numerical columns
dataset.describe()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
count,2928.00000,2928.000000,2928.000000,2928.000000,2735.000000,2928.000000,2375.000000,2928.000000,2896.000000,2928.000000,2909.000000,2702.000000,2909.000000,2928.000000,2485.000000,2.284000e+03,2896.000000,2896.000000,2768.000000,2768.000000
mean,2007.50000,69.224932,164.796448,30.407445,4.614856,740.321185,80.960842,2427.855874,38.235394,42.179303,82.548298,5.930163,82.321416,1.747712,7494.210719,1.276454e+07,4.850622,4.881423,0.627419,11.999639
std,4.61056,9.523867,124.292079,118.114450,4.050749,1990.930605,25.018337,11485.970937,19.959590,160.700547,23.416674,2.483273,23.706644,5.085542,14282.251492,6.103765e+07,4.420829,4.509609,0.210978,3.346440
min,2000.00000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.370000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000
25%,2003.75000,63.100000,74.000000,0.000000,0.905000,4.853964,77.000000,0.000000,19.300000,0.000000,78.000000,4.260000,78.000000,0.100000,463.852618,1.966738e+05,1.600000,1.575000,0.493000,10.100000
50%,2007.50000,72.100000,144.000000,3.000000,3.770000,65.611455,92.000000,17.000000,43.350000,4.000000,93.000000,5.750000,93.000000,0.100000,1764.973870,1.391756e+06,3.300000,3.400000,0.677000,12.300000
75%,2011.25000,75.700000,228.000000,22.000000,7.715000,442.614322,97.000000,362.250000,56.100000,28.000000,97.000000,7.490000,97.000000,0.800000,5932.899677,7.426746e+06,7.200000,7.200000,0.779250,14.300000
max,2015.00000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,77.600000,2500.000000,99.000000,17.600000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000

In [27]:
#Check for missing data in the data frame
dataset.isnull().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                      0
Adult Mortality                      0
infant deaths                        0
Alcohol                            193
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                32
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                443
Population                         644
 thinness  1-19 years               32
 thinness 5-9 years                 32
Income composition of resources    160
Schooling                          160
dtype: int64